import os
from typing import Any

__version__: str

class VitriError(Exception): ...
class ConfigError(VitriError): ...
class SpecError(VitriError): ...
class EnvError(VitriError): ...
class InputError(VitriError): ...
class MismatchError(VitriError): ...
class ConstructionError(VitriError): ...
class IoError(VitriError): ...

class Result:
    @property
    def status(self) -> str: ...
    @property
    def summary(self) -> dict[str, Any]: ...
    @property
    def files(self) -> dict[str, bytes]: ...
    @property
    def reduced_cnf(self) -> str: ...
    @property
    def vtree(self) -> str | None: ...
    def write(self, directory: str | os.PathLike[str]) -> None: ...

def prepare(
    dimacs: str | bytes,
    *,
    mode: str | None = None,
    vtree: str | None = None,
    budget_ms: int | None = None,
    components: str | None = None,
    candidates: int | None = None,
    simplify: bool | None = None,
    arjun: bool | None = None,
    dot: bool = False,
) -> Result: ...
def capabilities() -> dict[str, Any]: ...
